# please create a new token github.com/settings/tokens/new .
# give repo read write and workflow permissions to the token and store its value
# add the token as a repo secret with key GH_TOKEN_1 and value equal to token value stored above

name: Update Readme ascii graph and workflow with random cron interval
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@master
        with:
          ref: dev
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Create Chart
        run: |
          python codes/rating_chart.py > chart.txt
          CHART=$(cat chart.txt)
          echo "::set-output name=chart::$CHART"
          cat assets/README-1.md > README.md
          cat chart.txt >> README.md
          currentDate=`env TZ=Africa/Lagos date`
          printf "\nChart last updated - ${currentDate}" >> README.md
          cat assets/README-2.md >> README.md
      - name: Update workflow yaml file
        run: |
          python codes/generate_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          author_name: Adophilus
          author_email: uchenna19of@gmail.com
          message: "Auto updating my readme"
